cache = true
max_cache_age = "1d"
max_retries = 3
retry_wait_time = 2
timeout = 20
exclude_path = ["target"]
exclude = [
  "^https?://localhost",
  "^https?://127\\.0\\.0\\.1",
  "^https?://example\\.com",
  "/actions/workflows/.+/badge\\.svg$"
]
accept = [200, 206, 429]
